name: Django CI

on:
  push:
    branches: [ "main", "development"]
  pull_request:
    branches: [ "main", "development"]

jobs:
  build:

    runs-on: debian-11
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9.2]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117
        pip install -U spacy
        python -m spacy download en_core_web_sm
    - name: Run Tests
      run: |
        python manage.py test
